project_id = "lzxbhriamrnbfsymouyg"

[functions.send-sample-request]
verify_jwt = false

[functions.snov-get-lists]
verify_jwt = false

[functions.snov-send-campaign]
verify_jwt = false

[functions.snov-get-campaigns]
verify_jwt = false

[functions.send-beta-notification]
verify_jwt = false

[functions.snov-get-campaign-stats]
verify_jwt = false

[functions.send-beta-info-email]
verify_jwt = false
