project_id = "lzxbhriamrnbfsymouyg"

[functions.send-sample-request]
verify_jwt = false

[functions.snov-get-lists]
verify_jwt = false

[functions.snov-send-campaign]
verify_jwt = false

[functions.snov-get-campaigns]
verify_jwt = false

[functions.send-beta-notification]
verify_jwt = false

[functions.snov-get-campaign-stats]
verify_jwt = false

[functions.send-beta-info-email]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

[functions.send-trial-reminders]
verify_jwt = false

[functions.ai-generate-page]
verify_jwt = false

[functions.ai-rewrite-copy]
verify_jwt = false

[functions.ai-map-csv]
verify_jwt = false

[functions.notify-page-view]
verify_jwt = false

[functions.snov-enrich-linkedin]
verify_jwt = false

[functions.ai-assistant-chat]
verify_jwt = false
